#!/usr/bin/env python3
"""Audit a finite-link clockwork route to the required rank-one triplet lock.

No web lookup is used.

The dressed publication-card C5 scan shows that the crossed triplet inverse
block must be near rank one:

    W_kappa = U diag(1, kappa^-1, kappa^-1, kappa^-1) V^\dagger,
    kappa >= 300.

This script checks whether the hierarchy can be generated by a finite nearest-
neighbour link chain rather than by inserting a bare 300:1 singlet hierarchy.
For one orthogonal triplet direction, take holomorphic link constraints

    F_a = X_a - q X_{a+1},       a=0,...,n-1.

The null vector is proportional to (1, q^-1, ..., q^-n).  If the protected
crossed direction couples at the first site and the three orthogonal leakage
directions couple at the endpoint, the leakage is eps=q^-n and

    kappa = q^n.

The nonzero singular values of the constraint matrix test whether the link
sector itself introduced an exponentially light tower.  A complete or
constrained source/link realization is still required for threshold silence.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "rank_one_clockwork_locking"
C5_SCAN = ROOT / "output" / "publication_dressed_c5_kappa_scan" / "summary.json"
UV_AUDIT = ROOT / "output" / "uv_perturbativity_landau" / "uv_landau_audit_summary.json"

Q_GRID = [1.5, 1.75, 2.0, 2.2, 2.5, 3.0, 4.0]
MAX_N = 12
DISPLAY_ST = 1.0e-5


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def link_constraint_matrix(q: float, n: int) -> np.ndarray:
    """Return C_{a b}=delta_{a b}-q delta_{a,b-1}, shape n x (n+1)."""
    c = np.zeros((n, n + 1), dtype=float)
    for a in range(n):
        c[a, a] = 1.0
        c[a, a + 1] = -q
    return c


def normalized_zero_mode(q: float, n: int) -> np.ndarray:
    v = np.array([q ** (-a) for a in range(n + 1)], dtype=float)
    return v / np.linalg.norm(v)


def clockwork_row(q: float, n: int, c5: dict[str, Any], uv: dict[str, Any]) -> dict[str, Any]:
    kappa = q**n
    eps = 1.0 / kappa
    c = link_constraint_matrix(q, n)
    singulars = np.linalg.svd(c, compute_uv=False)
    zero = normalized_zero_mode(q, n)

    row30 = next(row for row in c5["scan_rows"] if abs(row["kappa"] - 30.0) < 1.0e-12)
    central_st30 = row30["central_global_STmax_1e35"]
    max_st30 = row30["max_width_global_STmax_1e35"]
    central_stmax = central_st30 * (kappa / 30.0)
    max_stmax = max_st30 * (kappa / 30.0)
    central_margin = (central_stmax / DISPLAY_ST) ** 2
    max_margin = (max_stmax / DISPLAY_ST) ** 2

    # If implemented with propagating complete 10+10bar links, three orthogonal
    # clockwork chains with n constraints use roughly 3(n+1) vectorlike pairs.
    # This is only a UV warning estimate; a constrained/composite realization has
    # zero additional propagating Dynkin index in the EFT.
    added_vector_pairs = 3 * (n + 1)
    delta_b10_vector10_pairs = 2.0 * added_vector_pairs
    minimal = next(s for s in uv["scenarios"] if s["name"] == "minimal_yukawa_higgs_plus_matter")
    b10_if_propagating_10_pairs = minimal["b10"] + delta_b10_vector10_pairs

    # Reconstruct the alpha_G^{-1} used in the UV audit from the minimal scenario.
    # landau_ratio=exp(2 pi alpha_inv/b10).
    alpha_inv = math.log(minimal["min_landau_ratio_over_displayed_R"]) * minimal["b10"] / (2.0 * math.pi)
    landau_ratio = math.exp(2.0 * math.pi * alpha_inv / b10_if_propagating_10_pairs)

    return {
        "q": q,
        "n": n,
        "kappa": kappa,
        "epsilon": eps,
        "passes_required_kappa": kappa >= c5["verdict"]["max_width_min_kappa_pass_1e35"],
        "zero_mode_endpoint_ratio": abs(zero[-1] / zero[0]),
        "nonzero_singular_min": float(np.min(singulars)),
        "nonzero_singular_max": float(np.max(singulars)),
        "nonzero_singular_condition": float(np.max(singulars) / np.min(singulars)),
        "central_STmax_1e35_extrapolated": central_stmax,
        "max_width_STmax_1e35_extrapolated": max_stmax,
        "central_margin_1e35_at_ST_1e_minus_5": central_margin,
        "max_width_margin_1e35_at_ST_1e_minus_5": max_margin,
        "passes_central_ST_1e_minus_5": central_margin >= 1.0,
        "passes_max_width_ST_1e_minus_5": max_margin >= 1.0,
        "three_chain_added_10_pairs_if_propagating": added_vector_pairs,
        "delta_b10_if_propagating_10_pairs": delta_b10_vector10_pairs,
        "b10_if_added_to_minimal": b10_if_propagating_10_pairs,
        "landau_ratio_if_propagating_10_pairs": landau_ratio,
        "reaches_R200_if_propagating_10_pairs": landau_ratio > 200.0,
    }


def direct_mechanism_scorecard(c5: dict[str, Any]) -> list[dict[str, Any]]:
    required = c5["verdict"]["max_width_min_kappa_pass_1e35"]
    return [
        {
            "mechanism": "bare_singlet_ratio",
            "equation": "M_perp/M_parallel = kappa",
            "minimal_requirement": f"M_perp/M_parallel >= {required:g}",
            "status": "tuned_unless_a_symmetry_fixes_the_ratio",
        },
        {
            "mechanism": "single_schur_denominator",
            "equation": "kappa = 1 + eta^2/R",
            "minimal_requirement": "with eta<=4, R <= eta^2/(kappa-1) = 5.35e-2",
            "status": "possible_but_introduces_a_sub_GUT_denominator_or_new_threshold",
        },
        {
            "mechanism": "finite_clockwork_link",
            "equation": "kappa = q^n",
            "minimal_requirement": "q=3,n=6 gives kappa=729; q=2,n=9 gives kappa=512",
            "status": "preferred_conditional_route_if_links_are_complete_or_constrained",
        },
    ]


def audit() -> dict[str, Any]:
    c5 = read_json(C5_SCAN)
    uv = read_json(UV_AUDIT)
    rows = [clockwork_row(q, n, c5, uv) for q in Q_GRID for n in range(1, MAX_N + 1)]
    passing = [
        row for row in rows
        if row["passes_required_kappa"] and row["passes_max_width_ST_1e_minus_5"]
    ]
    # The representative card is chosen to keep the nearest-neighbour ratio
    # genuinely order-one.  A shorter q=4,n=5 chain also works, but q=3,n=6 is
    # a cleaner moderate-coupling benchmark.
    preferred = min(
        passing,
        key=lambda row: (
            abs(row["q"] - 3.0),
            row["n"],
            row["nonzero_singular_condition"],
        ),
    )
    smallest_n_by_q = []
    for q in Q_GRID:
        qrows = [row for row in rows if row["q"] == q and row["passes_max_width_ST_1e_minus_5"]]
        if qrows:
            smallest_n_by_q.append(min(qrows, key=lambda row: row["n"]))

    return {
        "note": "No web lookup used. Conditional finite-link clockwork audit for the rank-one C5 locking requirement.",
        "input_required_kappa": c5["verdict"]["max_width_min_kappa_pass_1e35"],
        "display_ST": DISPLAY_ST,
        "formulae": {
            "constraint": "F_a = X_a - q X_{a+1}",
            "zero_mode": "v_a proportional q^{-a}",
            "leakage": "epsilon = |v_n/v_0| = q^{-n}",
            "kappa": "kappa = q^n",
            "C5_STmax_extrapolation": "S_T^max(kappa)=S_T^max(30)*(kappa/30)",
        },
        "mechanism_scorecard": direct_mechanism_scorecard(c5),
        "smallest_n_by_q": smallest_n_by_q,
        "preferred_clockwork_card": preferred,
        "rows": rows,
        "verdict": {
            "preferred_route": "finite_clockwork_link",
            "preferred_q": preferred["q"],
            "preferred_n": preferred["n"],
            "preferred_kappa": preferred["kappa"],
            "preferred_max_width_margin": preferred["max_width_margin_1e35_at_ST_1e_minus_5"],
            "main_caveat": (
                "This is a conditional source/link mechanism.  It closes the numerical kappa requirement only "
                "if the link fields are complete/degenerate, constrained, or composite so that their threshold "
                "and UV beta-function costs do not reintroduce the Landau-pole obstruction."
            ),
        },
    }


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fields = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_report(summary: dict[str, Any]) -> None:
    lines = [
        "# Rank-one clockwork locking audit",
        "",
        "No web lookup was used.",
        "",
        "The dressed publication-card C5 replay requires",
        f"`kappa >= {summary['input_required_kappa']:.0f}`.",
        "",
        "For a finite link chain with `F_a = X_a - q X_{a+1}`, the zero mode has",
        "`v_a proportional q^{-a}`.  Endpoint leakage is therefore",
        "`epsilon=q^{-n}` and `kappa=q^n`.",
        "",
        "## Mechanism scorecard",
        "",
        "| mechanism | equation | requirement | status |",
        "|---|---|---|---|",
    ]
    for row in summary["mechanism_scorecard"]:
        lines.append(
            f"| `{row['mechanism']}` | `{row['equation']}` | "
            f"{row['minimal_requirement']} | {row['status']} |"
        )
    lines += [
        "",
        "## Smallest passing chain by q",
        "",
        "| q | n | kappa | endpoint epsilon | max-width margin at S_T=1e-5 | link singular cond. | LP/MG if 10-pairs propagate |",
        "|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in summary["smallest_n_by_q"]:
        lines.append(
            f"| {row['q']:.2f} | {row['n']} | {row['kappa']:.6g} | "
            f"{row['epsilon']:.6e} | {row['max_width_margin_1e35_at_ST_1e_minus_5']:.6f} | "
            f"{row['nonzero_singular_condition']:.6f} | "
            f"{row['landau_ratio_if_propagating_10_pairs']:.6f} |"
        )
    p = summary["preferred_clockwork_card"]
    lines += [
        "",
        "## Preferred conditional card",
        "",
        f"`q={p['q']:.2f}`, `n={p['n']}`, `kappa={p['kappa']:.6g}`, "
        f"`epsilon={p['epsilon']:.6e}`.",
        "",
        f"Max-width 1e35 margin at `S_T=1e-5`: `{p['max_width_margin_1e35_at_ST_1e_minus_5']:.6f}`.",
        "",
        summary["verdict"]["main_caveat"],
        "",
    ]
    (OUT / "report.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    summary = audit()
    (OUT / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_csv(OUT / "clockwork_scan.csv", summary["rows"])
    write_report(summary)
    p = summary["preferred_clockwork_card"]
    print("Rank-one clockwork locking audit")
    print(f"  required kappa: {summary['input_required_kappa']:.0f}")
    print(f"  preferred q,n: {p['q']:.2f}, {p['n']}")
    print(f"  preferred kappa: {p['kappa']:.6g}")
    print(f"  max-width margin: {p['max_width_margin_1e35_at_ST_1e_minus_5']:.6f}")
    print(f"  wrote: {OUT}")


if __name__ == "__main__":
    main()
