#!/usr/bin/env python3
"""Component-spectrum audit for the Schur-locking auxiliary sector.

This is the representation-theory follow-up to the finite charge ledger.  The
charge audit proves that the polynomial lock

    W = Tr X(AB-I_A) + Tr Z(C-BU_D) + Tr Y(G-G0-V_D C)

can be protected by a small grading.  This script asks the next question:
what threshold is generated by the fields that carry those symbols?

The conservative branch treats B,C,X,Y,Z,I_A as gauge-singlet auxiliary
matrices and embeds the active triplet bridge in a degenerate sterile 10'_G
whose doublet partner is inert.  The script also evaluates the fallback
branches in which the active bridge is only a triplet pair, or in which large
54/210 driver multiplets are propagating above M_G.
"""

from __future__ import annotations

import csv
import json
import math
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "code"))

import scan_yukawa_superpotential_rge as base  # noqa: E402


OUT = ROOT / "output" / "schur_auxiliary_component_spectrum"

# N=1 chiral superfield beta vectors in MSSM normalization.
B_SINGLET = np.array([0.0, 0.0, 0.0], dtype=float)
B_TRIPLET_PAIR = np.array([2.0 / 5.0, 0.0, 1.0], dtype=float)
B_DOUBLET_PAIR = np.array([3.0 / 5.0, 1.0, 0.0], dtype=float)
B_FIVE_PAIR = B_TRIPLET_PAIR + B_DOUBLET_PAIR
B_54_PAIR = np.array([24.0, 24.0, 24.0], dtype=float)
B_210_PAIR = np.array([112.0, 112.0, 112.0], dtype=float)
B_REL_SOURCE_54_BLOCK = np.array([132.0, 132.0, 132.0], dtype=float)
B_XIN_NORMAL_PAIR = np.array([68.0 / 5.0, 12.0, 16.0], dtype=float)

KAPPA_GRID = [0.3, 0.5, 0.9, 0.99, 1.0, 1.01, 1.1, 2.0, 3.0]
TOLS = [1.0e-2, 1.0e-3]


def projected_l2(vec: np.ndarray) -> float:
    return float(np.linalg.norm(base.PROJECTOR @ vec))


def delta(beta: np.ndarray, kappa: float) -> np.ndarray:
    return beta * math.log(1.0 / kappa) / (2.0 * math.pi)


def clean_window(beta: np.ndarray, tol: float) -> Dict[str, float]:
    p = projected_l2(beta)
    if p == 0.0:
        return {
            "projected_tol": tol,
            "projected_beta_l2": 0.0,
            "max_abs_log_kappa": math.inf,
            "kappa_min": 0.0,
            "kappa_max": math.inf,
        }
    width = 2.0 * math.pi * tol / p
    return {
        "projected_tol": tol,
        "projected_beta_l2": p,
        "max_abs_log_kappa": width,
        "kappa_min": math.exp(-width),
        "kappa_max": math.exp(width),
    }


def landau_ratio(alpha_inv: float, sum_t: float) -> float:
    b10 = sum_t - 24.0
    if b10 <= 0:
        return math.inf
    return math.exp(2.0 * math.pi * alpha_inv / b10)


def component_rows() -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = [
        {
            "symbol": "B,C,X,Y,Z,I_A",
            "spin10_status": "gauge-singlet auxiliary matrices",
            "sm_or_ps_content": "(1,1,1)",
            "beta_vector": B_SINGLET.tolist(),
            "projected_beta_l2": projected_l2(B_SINGLET),
            "classification": "gauge singlet",
            "verdict": "PASS: no SM threshold",
        },
        {
            "symbol": "G,G0,U_D,V_D,U_L,V_L",
            "spin10_status": "sterile 10'_G + conjugate, degenerate 5+5bar",
            "sm_or_ps_content": "D+Dbar plus inert L+Lbar",
            "beta_vector": B_FIVE_PAIR.tolist(),
            "projected_beta_l2": projected_l2(B_FIVE_PAIR),
            "classification": "complete SU(5) pair",
            "verdict": "PASS if the 10'_G pair is degenerate",
        },
        {
            "symbol": "U_D,V_D only",
            "spin10_status": "post-Spin(10) triplet-only remnant",
            "sm_or_ps_content": "(3,1,-1/3)+(bar3,1,+1/3)",
            "beta_vector": B_TRIPLET_PAIR.tolist(),
            "projected_beta_l2": projected_l2(B_TRIPLET_PAIR),
            "classification": "incomplete threshold",
            "verdict": "FAIL unless mass-locked near M_G",
        },
        {
            "symbol": "54 link/driver pair",
            "spin10_status": "complete 54+54_D",
            "sm_or_ps_content": "24+15+15bar repeated as full Spin(10) pair",
            "beta_vector": B_54_PAIR.tolist(),
            "projected_beta_l2": projected_l2(B_54_PAIR),
            "classification": "complete multiplet",
            "verdict": "projected-threshold silent, but contributes to SO(10) UV beta",
        },
        {
            "symbol": "210 link/driver pair",
            "spin10_status": "complete 210+210_D",
            "sm_or_ps_content": "1+5+5bar+10+10bar+24+40+40bar+75 pair",
            "beta_vector": B_210_PAIR.tolist(),
            "projected_beta_l2": projected_l2(B_210_PAIR),
            "classification": "complete multiplet",
            "verdict": "projected-threshold silent, but contributes strongly to SO(10) UV beta",
        },
        {
            "symbol": "W_rel 54 source block",
            "spin10_status": "eleven complete 54 fields",
            "sm_or_ps_content": "full 54 repeated across the relative-alignment Hessian",
            "beta_vector": B_REL_SOURCE_54_BLOCK.tolist(),
            "projected_beta_l2": projected_l2(B_REL_SOURCE_54_BLOCK),
            "classification": "complete multiplet block",
            "verdict": "projected-threshold silent; UV Landau risk if propagating at M_G",
        },
        {
            "symbol": "Xi_N fallback",
            "spin10_status": "propagating normal-pair multiplier",
            "sm_or_ps_content": "incomplete effective normal-pair spectrum",
            "beta_vector": B_XIN_NORMAL_PAIR.tolist(),
            "projected_beta_l2": projected_l2(B_XIN_NORMAL_PAIR),
            "classification": "incomplete threshold",
            "verdict": "requires tight mass locking or auxiliary/composite interpretation",
        },
    ]
    return rows


def threshold_rows() -> List[Dict[str, Any]]:
    branches = [
        ("singlet_auxiliaries", B_SINGLET, "no threshold"),
        ("degenerate_10G_5pair", B_FIVE_PAIR, "universal only"),
        ("triplet_only_bridge", B_TRIPLET_PAIR, "non-universal"),
        ("complete_54_pair", B_54_PAIR, "universal only"),
        ("complete_210_pair", B_210_PAIR, "universal only"),
        ("Wrel_54_source_block", B_REL_SOURCE_54_BLOCK, "universal only"),
        ("XiN_incomplete_fallback", B_XIN_NORMAL_PAIR, "non-universal"),
    ]
    rows: List[Dict[str, Any]] = []
    for name, beta, status in branches:
        for kappa in KAPPA_GRID:
            d = delta(beta, kappa)
            rows.append(
                {
                    "branch": name,
                    "kappa_M_over_MG": kappa,
                    "threshold_status": status,
                    "delta": d.tolist(),
                    "projected_delta_l2": projected_l2(d),
                    "universal_delta": float(np.mean(d)),
                }
            )
    return rows


def window_rows() -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for name, beta in [
        ("triplet_only_bridge", B_TRIPLET_PAIR),
        ("XiN_incomplete_fallback", B_XIN_NORMAL_PAIR),
    ]:
        for tol in TOLS:
            row = clean_window(beta, tol)
            row["branch"] = name
            rows.append(row)
    return rows


def uv_rows() -> List[Dict[str, Any]]:
    # Local UV audit used alpha_G^{-1}=41.363... at the R=200 corrected branch.
    alpha_ref = 41.36308203884868
    scenarios = [
        ("baseline_minimal_yukawa_higgs_matter", 70.0, "three 16s plus 10_H,120_H,126bar_H"),
        ("baseline_plus_sterile_10G", 71.0, "minimal Schur completion adds T(10)=1"),
        ("documented_complete_drive_pairs", 184.0, "three 54 link/driver pairs plus one 210 pair"),
        ("documented_drive_pairs_plus_10G", 185.0, "drive-pair branch plus sterile 10'_G"),
        ("Wrel_source_blocks", 300.0, "eleven-field 54 relative-source block plus 210 source block"),
    ]
    rows = []
    for name, sum_t, interp in scenarios:
        b10 = sum_t - 24.0
        lp = landau_ratio(alpha_ref, sum_t)
        rows.append(
            {
                "scenario": name,
                "sum_T": sum_t,
                "b10": b10,
                "alphaG_inv_ref": alpha_ref,
                "landau_ratio_Lambda_over_MG": lp,
                "reaches_R50": bool(lp > 50.0),
                "reaches_R200": bool(lp > 200.0),
                "interpretation": interp,
            }
        )
    return rows


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    fields = sorted({key for row in rows for key in row.keys()})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            out = dict(row)
            for key, value in list(out.items()):
                if isinstance(value, list):
                    out[key] = " ".join(f"{float(x):.12e}" for x in value)
            writer.writerow(out)


def make_report(payload: Dict[str, Any]) -> str:
    lines = [
        "# Schur auxiliary component-spectrum audit",
        "",
        "No web lookup was used.",
        "",
        "## Component classification",
        "",
        "| symbols | status | beta vector | projected beta l2 | verdict |",
        "|---|---|---:|---:|---|",
    ]
    for row in payload["components"]:
        lines.append(
            f"| `{row['symbol']}` | {row['classification']} | `{row['beta_vector']}` | "
            f"{row['projected_beta_l2']:.6e} | {row['verdict']} |"
        )
    lines.extend(
        [
            "",
            "## Clean windows for incomplete branches",
            "",
            "| branch | tolerance | kappa min | kappa max | |log kappa|max |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for row in payload["windows"]:
        lines.append(
            f"| `{row['branch']}` | {row['projected_tol']:.1e} | "
            f"{row['kappa_min']:.6f} | {row['kappa_max']:.6f} | "
            f"{row['max_abs_log_kappa']:.6e} |"
        )
    lines.extend(
        [
            "",
            "## UV perturbativity check",
            "",
            "| scenario | sum T | b10 | LP/MG | reaches R=50 | reaches R=200 |",
            "|---|---:|---:|---:|---:|---:|",
        ]
    )
    for row in payload["uv"]:
        lines.append(
            f"| `{row['scenario']}` | {row['sum_T']:.0f} | {row['b10']:.0f} | "
            f"{row['landau_ratio_Lambda_over_MG']:.3g} | {row['reaches_R50']} | {row['reaches_R200']} |"
        )
    lines.extend(
        [
            "",
            "## Verdict",
            "",
            payload["verdict"],
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    components = component_rows()
    thresholds = threshold_rows()
    windows = window_rows()
    uv = uv_rows()

    payload: Dict[str, Any] = {
        "note": "No web lookup used. Schur-locking component-spectrum audit.",
        "components": components,
        "threshold_scan": thresholds,
        "windows": windows,
        "uv": uv,
        "minimal_branch": {
            "definition": "B,C,X,Y,Z,I_A are gauge singlets; G,U,V live in a degenerate sterile 10'_G; U_L,V_L are inert doublet partners.",
            "projected_threshold_l2": 0.0,
            "new_so10_dynkin_index": 1.0,
            "landau_ratio_with_baseline": next(
                row["landau_ratio_Lambda_over_MG"]
                for row in uv
                if row["scenario"] == "baseline_plus_sterile_10G"
            ),
        },
        "verdict": (
            "The Schur-locking auxiliary sector is threshold-safe only on the "
            "minimal-singlet plus degenerate-10'_G branch: the new projected "
            "threshold is zero and the SO(10) Dynkin-index increment is just "
            "T(10)=1.  A post-Spin(10) triplet-only bridge is a controlled EFT "
            "fallback but must be mass-locked within the displayed kappa window.  "
            "Promoting the large 54/210 source/driver sector to propagating "
            "multiplets remains the UV Landau-pole obstruction rather than a "
            "one-loop matching obstruction."
        ),
    }

    write_csv(OUT / "component_classification.csv", components)
    write_csv(OUT / "branch_threshold_scan.csv", thresholds)
    write_csv(OUT / "clean_windows.csv", windows)
    write_csv(OUT / "uv_perturbativity_rows.csv", uv)
    (OUT / "summary.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (OUT / "report.md").write_text(make_report(payload), encoding="utf-8")

    minimal = payload["minimal_branch"]
    triplet_window = next(row for row in windows if row["branch"] == "triplet_only_bridge" and row["projected_tol"] == 1.0e-2)
    print("Schur auxiliary component-spectrum audit complete")
    print(f"minimal_projected_threshold_l2={minimal['projected_threshold_l2']:.3e}")
    print(f"minimal_new_T={minimal['new_so10_dynkin_index']:.1f}")
    print(f"baseline_plus_10G_LP_over_MG={minimal['landau_ratio_with_baseline']:.3g}")
    print(
        "triplet_only_window_1e-2="
        f"[{triplet_window['kappa_min']:.6f},{triplet_window['kappa_max']:.6f}]"
    )
    print(f"outputs={OUT}")


if __name__ == "__main__":
    main()
