#!/usr/bin/env python3
"""Route-E dependency-closure audit.

Removes the four classical-input citations (CI-1..CI-4) of the Route-E paper
by direct computation, and closes the enumeration over ALL simple algebras of
rank 4-15 (not only the complex-representation families):

  1. Root systems from Cartan matrices (A/B/C/D/E6/E7/E8/F4), with positive
     root counts as self-tests.
  2. CI-1 removal: longest Weyl element w0 computed by rho-descent; the
     conjugation involution iota = -w0 is read off, machine-deriving the
     self-conjugacy rules (A_n label reversal, D_odd spinor swap, E6 arm
     swap, all other families w0 = -1 hence no complex irreps).
  3. Full enumeration, dim <= 16, every simple algebra of rank 4-15 plus
     E6/E7/E8/F4 (generic exact Weyl dimension engine): the complex list is
     unchanged, and the so(9) REAL spinor 16 and so(15) REAL vector 15 are
     recorded as near-misses that fail chirality, not dimension.
  4. CI-4 removal: exceptional minima by scan: E6 = 27, E7 = 56, F4 = 26,
     E8 = 248.  Rank >= 16 corroborated by fundamental/vector dims at rank 16
     (17, 33, 32, 32); minimality for all higher ranks stays textbook-cited.
  5. CI-2 removal: exact integer cubic traces for SU(15)/SU(16) fundamentals
     (nonzero -> gauge-anomalous single-Weyl content).
  6. CI-3 removal: the chiral 16 of Spin(10) built from five fermionic modes
     (32-dim Fock space, chirality = occupation parity); the symmetrized
     cubic trace tr({T_a,T_b}T_c) vanishes over ALL 45^3 generator triples;
     the 16-block Cartan weights reproduce the demicube of the paper's
     Appendix A.

Boundary: the Witten global anomaly (pi_4(Spin(10)) = 0) is cited, not
computed; Frobenius-Schur types (real vs pseudoreal) are not computed (only
self-conjugacy is needed); rank >= 17 minimal dimensions are textbook-cited;
zeta is not derived; no PSLT-only unconditional GUT proof is claimed.
"""

from __future__ import annotations

from fractions import Fraction as Fr
from itertools import product
from pathlib import Path
import json

import numpy as np

CHECKS: list[tuple[str, bool]] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    CHECKS.append((name, bool(ok)))
    line = f"[{'PASS' if ok else 'FAIL'}] {name}"
    if detail:
        line += f"   ({detail})"
    print(line)


# ------------------------------------------------------------- Cartan data
def cartan_A(n):
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        C[i][i] = 2
        if i + 1 < n:
            C[i][i + 1] = C[i + 1][i] = -1
    return C


def cartan_B(n):                     # so(2n+1): alpha_n short, C_{n-1,n} = -2
    C = cartan_A(n)
    C[n - 2][n - 1] = -2
    C[n - 1][n - 2] = -1
    return C


def cartan_C(n):                     # sp(2n): transpose of B_n
    C = cartan_A(n)
    C[n - 2][n - 1] = -1
    C[n - 1][n - 2] = -2
    return C


def cartan_D(n):                     # so(2n): fork at node n-3 (0-indexed)
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        C[i][i] = 2
    for i in range(n - 2):
        if i + 1 < n - 1:
            C[i][i + 1] = C[i + 1][i] = -1
    C[n - 3][n - 1] = C[n - 1][n - 3] = -1
    return C


def cartan_tree(arms):
    """Simply-laced tree: paths of vertex-lengths p,q,r glued at one end.
    T(3,3,2)=E6, T(4,3,2)=E7, T(5,3,2)=E8, T(2,2,2)=D4."""
    nodes = 1 + sum(a - 1 for a in arms)
    C = [[0] * nodes for _ in range(nodes)]
    for i in range(nodes):
        C[i][i] = 2
    idx = 1
    for a in arms:
        prev = 0
        for _ in range(a - 1):
            C[prev][idx] = C[idx][prev] = -1
            prev = idx
            idx += 1
    return C


def cartan_F4():
    C = cartan_A(4)
    C[1][2] = -2                     # middle double bond
    C[2][1] = -1
    return C


# --------------------------------------------------- root system machinery
def positive_roots(C):
    """Positive roots in simple-root coordinates, generated by height."""
    n = len(C)
    roots = {tuple(1 if j == i else 0 for j in range(n)) for i in range(n)}
    level = list(roots)
    allroots = set(roots)
    while level:
        nxt = set()
        for beta in level:
            pairing = [sum(beta[j] * C[j][i] for j in range(n)) for i in range(n)]
            for i in range(n):
                p = 0
                cur = list(beta)
                while True:
                    cur[i] -= 1
                    if cur[i] < 0 or tuple(cur) not in allroots:
                        break
                    p += 1
                if p - pairing[i] >= 1:
                    cand = list(beta)
                    cand[i] += 1
                    cand = tuple(cand)
                    if cand not in allroots:
                        nxt.add(cand)
        allroots |= nxt
        level = list(nxt)
    return sorted(allroots)


def symmetrizers(C):
    """d_i with d_j C_ij = d_i C_ji (connected diagram assumed)."""
    n = len(C)
    d = [None] * n
    d[0] = Fr(1)
    todo = [0]
    while todo:
        i = todo.pop()
        for j in range(n):
            if i != j and C[i][j] != 0 and d[j] is None:
                d[j] = d[i] * Fr(C[j][i], C[i][j])
                todo.append(j)
    return d


def weyl_dim(posroots, d, labels):
    dim = Fr(1)
    for c in posroots:
        num = sum(c[j] * d[j] * (labels[j] + 1) for j in range(len(labels)))
        den = sum(c[j] * d[j] for j in range(len(labels)))
        dim *= Fr(num, den)
    return dim


def w0_involution(C, n_pos):
    """rho-descent word for w0; returns (word_length, sigma) where sigma is
    the permutation with -w0(omega_m) = omega_sigma(m), or None if -w0 != perm."""
    n = len(C)
    v = [1] * n
    word = []
    while any(x > 0 for x in v):
        i = next(k for k in range(n) if v[k] > 0)
        ai = v[i]
        v = [v[j] - ai * C[i][j] for j in range(n)]
        word.append(i)

    def apply_word(u):
        u = list(u)
        for i in word:
            ui = u[i]
            u = [u[j] - ui * C[i][j] for j in range(n)]
        return u

    sigma = []
    for m in range(n):
        img = [-x for x in apply_word([1 if k == m else 0 for k in range(n)])]
        if sorted(img) != [0] * (n - 1) + [1]:
            return len(word), None
        sigma.append(img.index(1))
    return len(word), tuple(sigma)


def enumerate_reps(rank, dimfun, cap):
    out = []

    def rec(prefix):
        if len(prefix) == rank:
            if any(prefix):
                dd = dimfun(prefix)
                if dd <= cap:
                    out.append((tuple(prefix), int(dd)))
            return
        k = 0
        while True:
            cand = prefix + [k]
            probe = tuple(cand + [0] * (rank - len(cand)))
            if any(probe) and dimfun(probe) > cap:
                break
            rec(cand)
            k += 1

    rec([])
    return out


# ---------------------------------------------------------------- section 1
print("== Section 1: root systems from Cartan matrices (self-tests) ==")

ALGS = {}
for n in range(4, 16):
    ALGS[f"A{n}"] = cartan_A(n)
    ALGS[f"B{n}"] = cartan_B(n)
    ALGS[f"C{n}"] = cartan_C(n)
    ALGS[f"D{n}"] = cartan_D(n)
ALGS["E6"] = cartan_tree((3, 3, 2))
ALGS["E7"] = cartan_tree((4, 3, 2))
ALGS["E8"] = cartan_tree((5, 3, 2))
ALGS["F4"] = cartan_F4()

POS, DSYM = {}, {}
for name, C in ALGS.items():
    POS[name] = positive_roots(C)
    DSYM[name] = symmetrizers(C)

expected_counts = {"A": lambda n: n * (n + 1) // 2, "B": lambda n: n * n,
                   "C": lambda n: n * n, "D": lambda n: n * (n - 1)}
ok_counts = all(
    len(POS[f"{f}{n}"]) == expected_counts[f](n)
    for f in "ABCD" for n in range(4, 16)
) and len(POS["E6"]) == 36 and len(POS["E7"]) == 63 \
    and len(POS["E8"]) == 120 and len(POS["F4"]) == 24
check("positive-root counts match (A,B,C,D rank 4-15; E6=36, E7=63, E8=120, F4=24)",
      ok_counts)


def dim_of(name, labels):
    return weyl_dim(POS[name], DSYM[name], list(labels))


anchors = [
    ("A15", (1,) + (0,) * 14, 16), ("A4", (2, 0, 0, 0), 15),
    ("A5", (0, 1, 0, 0, 0), 15), ("D5", (0, 0, 0, 0, 1), 16),
    ("D5", (1, 0, 0, 0, 0), 10), ("D5", (0, 1, 0, 0, 0), 45),
    ("B4", (1, 0, 0, 0), 9), ("B4", (0, 0, 0, 1), 16),
    ("C4", (1, 0, 0, 0), 8), ("D7", (0, 0, 0, 0, 0, 0, 1), 64),
]
check("dimension anchors (incl. so(9): vector 9, spinor 16; sp(8) fund 8)",
      all(dim_of(nm, lb) == dd for nm, lb, dd in anchors))

# ---------------------------------------------------------------- section 2
print("== Section 2: CI-1 removal -- w0 and the conjugation involution ==")

sigma_table = {}
ok_len = True
for name, C in ALGS.items():
    ln, sigma = w0_involution(C, len(POS[name]))
    ok_len &= (ln == len(POS[name]))
    sigma_table[name] = sigma
check("rho-descent word length = number of positive roots (all algebras)", ok_len)

ok_A = all(sigma_table[f"A{n}"] == tuple(range(n - 1, -1, -1)) for n in range(4, 16))
check("A_n: -w0 = label reversal (complex-rep rule machine-derived)", ok_A)
ok_Dodd = all(
    sigma_table[f"D{n}"] == tuple(range(n - 2)) + (n - 1, n - 2)
    for n in (5, 7, 9, 11, 13, 15)
)
check("D_odd: -w0 = spinor-node swap (machine-derived)", ok_Dodd)
ok_selfconj = all(
    sigma_table[f"{f}{n}"] == tuple(range(n))
    for f, ns in (("B", range(4, 16)), ("C", range(4, 16)), ("D", (4, 6, 8, 10, 12, 14)))
    for n in ns
) and sigma_table["E7"] == tuple(range(7)) \
    and sigma_table["E8"] == tuple(range(8)) and sigma_table["F4"] == tuple(range(4))
check("B, C, D_even, E7, E8, F4: w0 = -1, hence NO complex irreps (machine-derived)",
      ok_selfconj)
sE6 = sigma_table["E6"]
check("E6: -w0 is the nontrivial diagram flip (complex irreps exist)",
      sE6 is not None and sE6 != tuple(range(6))
      and all(sE6[sE6[k]] == k for k in range(6)), f"sigma = {sE6}")

# ---------------------------------------------------------------- section 3
print("== Section 3: full enumeration, dim <= 16, ALL simple algebras rank 4-15 ==")

CAP = 16
complex_found, selfconj_found = [], []
for name in ALGS:
    rank = len(ALGS[name])
    sigma = sigma_table[name]
    for lab, dd in enumerate_reps(rank, lambda a, nm=name: dim_of(nm, a), CAP):
        conj = tuple(lab[sigma[k]] for k in range(rank))
        if conj != lab:
            complex_found.append((name, lab, dd))
        else:
            selfconj_found.append((name, lab, dd))

complex_15_16 = sorted((nm, lab, dd) for nm, lab, dd in complex_found if dd >= 15)
exp_complex = {
    ("A4", (2, 0, 0, 0), 15), ("A4", (0, 0, 0, 2), 15),
    ("A5", (0, 1, 0, 0, 0), 15), ("A5", (0, 0, 0, 1, 0), 15),
    ("A14", (1,) + (0,) * 13, 15), ("A14", (0,) * 13 + (1,), 15),
    ("A15", (1,) + (0,) * 14, 16), ("A15", (0,) * 14 + (1,), 16),
    ("D5", (0, 0, 0, 1, 0), 16), ("D5", (0, 0, 0, 0, 1), 16),
}
check("complex irreps at dim 15/16 over ALL rank 4-15 algebras = the previous list",
      set(complex_15_16) == exp_complex,
      f"{len(complex_15_16)} entries")
check("no complex irrep of dim <= 16 from B, C, D_even, E, F families",
      all(nm[0] in ("A", "D") for nm, _, _ in complex_found)
      and all(nm not in ("E6", "E7", "E8", "F4") for nm, _, _ in complex_found))
check("near-miss ledger: so(9) spinor 16 exists but is SELF-CONJUGATE (fails chirality)",
      ("B4", (0, 0, 0, 1), 16) in selfconj_found)
check("near-miss ledger: so(15) vector 15 exists but is SELF-CONJUGATE",
      ("B7", (1, 0, 0, 0, 0, 0, 0), 15) in selfconj_found)

# ---------------------------------------------------------------- section 4
print("== Section 4: CI-4 removal -- exceptional minima; rank >= 16 corroboration ==")

e6_scan = enumerate_reps(6, lambda a: dim_of("E6", a), 27)
check("E6: minimal nontrivial irreps are exactly the two conjugate 27s",
      sorted(dd for _, dd in e6_scan) == [27, 27],
      f"{e6_scan}")
e7_scan = enumerate_reps(7, lambda a: dim_of("E7", a), 56)
check("E7: minimal nontrivial irrep = 56", sorted(dd for _, dd in e7_scan) == [56])
f4_scan = enumerate_reps(4, lambda a: dim_of("F4", a), 26)
check("F4: minimal nontrivial irrep = 26", sorted(dd for _, dd in f4_scan) == [26])
e8_scan = enumerate_reps(8, lambda a: dim_of("E8", a), 248)
check("E8: minimal nontrivial irrep = 248 (adjoint)",
      sorted(dd for _, dd in e8_scan) == [248])

C16 = {"A16": cartan_A(16), "B16": cartan_B(16), "C16": cartan_C(16),
       "D16": cartan_D(16)}
dims16 = {}
for nm, C in C16.items():
    pos = positive_roots(C)
    d = symmetrizers(C)
    dims16[nm] = int(weyl_dim(pos, d, [1] + [0] * 15))
check("rank-16 fundamental/vector dims: A16=17, B16=33, C16=32, D16=32 (all > 16)",
      dims16 == {"A16": 17, "B16": 33, "C16": 32, "D16": 32}, f"{dims16}")
print("ledger: minimality of these smallest irreps for every rank >= 16 is")
print("        textbook-cited (Slansky tables), not recomputed here.")

# ---------------------------------------------------------------- section 5
print("== Section 5: CI-2 removal -- SU(N) fundamental cubic trace (exact) ==")

for N in (15, 16):
    T = [N - 1] + [-1] * (N - 1)          # traceless diagonal generator
    tr3 = sum(t ** 3 for t in T)
    check(f"SU({N}) fundamental: tr T^3 = {tr3} != 0 -> single-Weyl content anomalous",
          sum(T) == 0 and tr3 != 0)

# ---------------------------------------------------------------- section 6
print("== Section 6: CI-3 removal -- the chiral 16 of Spin(10), all 45^3 triples ==")

NMODE = 5
DIM = 1 << NMODE
b = []
for k in range(NMODE):
    M = np.zeros((DIM, DIM), dtype=complex)
    for s in range(DIM):
        if s & (1 << k):
            sign = (-1) ** bin(s & ((1 << k) - 1)).count("1")
            M[s ^ (1 << k), s] = sign
    b.append(M)
bd = [M.conj().T for M in b]

Gam = []
for k in range(NMODE):
    Gam.append(b[k] + bd[k])
    Gam.append(-1j * (b[k] - bd[k]))

ok_cliff = all(
    np.allclose(Gam[a] @ Gam[c] + Gam[c] @ Gam[a], 2 * np.eye(DIM) * (a == c))
    for a in range(10) for c in range(a, 10)
)
check("Clifford algebra {Gamma_a, Gamma_b} = 2 delta_ab on the 32-dim Fock space",
      ok_cliff)

chir = (-1j) ** 5 * np.linalg.multi_dot(Gam)
parity = np.diag([(-1) ** bin(s).count("1") for s in range(DIM)]).astype(complex)
ok_chir = np.allclose(chir, parity) or np.allclose(chir, -parity)
check("chirality operator = occupation parity (up to overall sign)", ok_chir)

even_states = [s for s in range(DIM) if bin(s).count("1") % 2 == 0]
E = np.zeros((DIM, 16), dtype=complex)
for col, s in enumerate(even_states):
    E[s, col] = 1.0

gens16 = []
for a in range(10):
    for c in range(a + 1, 10):
        M = (-1j / 4) * (Gam[a] @ Gam[c] - Gam[c] @ Gam[a])
        gens16.append(E.conj().T @ M @ E)
gens16 = np.array(gens16)
check("45 generators projected to the even-parity chiral 16", len(gens16) == 45)

AB = np.einsum("aij,bjk->abik", gens16, gens16)
S = np.einsum("abij,cji->abc", AB, gens16)
S = S + S.transpose(1, 0, 2)                    # tr({T_a,T_b}T_c)
maxS = float(np.max(np.abs(S)))
check("cubic anomaly tensor of the 16 vanishes: max |tr({T_a,T_b}T_c)| = 0",
      maxS < 1e-9, f"max |S| = {maxS:.2e} over 45^3 triples")

cartan_idx = [0, 17, 30, 39, 44]                # T_{12},T_{34},T_{56},T_{78},T_{9 10}
Hs = gens16[cartan_idx]
ok_diag = all(np.allclose(H, np.diag(np.diag(H))) for H in Hs)
weights = sorted(tuple(round(float(np.real(Hs[k][i, i])) * 2) / 2 for k in range(5))
                 for i in range(16))
demicube = sorted(tuple(v / 2 for v in s) for s in product((1, -1), repeat=5)
                  if s.count(-1) % 2 == 0)
check("Cartan weights of the chiral block = the demicube of Appendix A",
      ok_diag and weights == demicube)

idx2 = float(np.real(np.trace(gens16[0] @ gens16[0])))
# 16 Cartan eigenvalues are +-1/2, so tr(H^2) = 16/4 = 4; the vector 10 has
# eigenvalues +-1 in one plane, tr(H^2) = 2; the ratio 4/2 = 2 is the
# standard Dynkin index of the 16 relative to the vector.
check("second-order index sanity: tr(H^2)|_16 = 4, i.e. index(16)/index(10) = 2",
      abs(idx2 - 4.0) < 1e-12, f"tr(T12^2) = {idx2}, ratio to vector = {idx2 / 2}")

# ---------------------------------------------------------------- ledger
npass = sum(1 for _, ok in CHECKS if ok)
all_pass = npass == len(CHECKS)

report = {
    "checks_total": len(CHECKS),
    "checks_passed": npass,
    "all_pass": all_pass,
    "checks": [{"name": name, "pass": ok} for name, ok in CHECKS],
    "sigma_involutions": {nm: (list(s) if s else "w0=-1")
                          for nm, s in sigma_table.items()},
    "complex_irreps_dim15_16_all_rank4_15": [
        {"algebra": nm, "labels": list(lab), "dim": dd}
        for nm, lab, dd in complex_15_16],
    "selfconjugate_near_misses": [
        {"algebra": nm, "labels": list(lab), "dim": dd}
        for nm, lab, dd in sorted(selfconj_found) if dd >= 15],
    "exceptional_minima": {"E6": 27, "E7": 56, "F4": 26, "E8": 248},
    "rank16_fundamental_dims": dims16,
    "su_fund_cubic_traces": {f"SU({N})": sum(t ** 3 for t in ([N - 1] + [-1] * (N - 1)))
                             for N in (15, 16)},
    "spin10_16_max_cubic_trace": maxS,
    # negative-boundary flags
    "witten_global_anomaly_cited_not_computed": True,
    "frobenius_schur_types_computed": False,
    "rank_ge_17_min_dims_cited_not_computed": True,
    "zeta_value_derived": False,
    "pslt_only_unconditional_gut_proof_claimed": False,
}

out_dir = Path(__file__).resolve().parents[1] / "output"
out_dir.mkdir(parents=True, exist_ok=True)
json_path = out_dir / "route_e_dependency_closure.json"
md_path = out_dir / "route_e_dependency_closure.md"
json_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
md_path.write_text(
    "# Route-E Dependency-Closure Audit\n\n"
    f"`{npass}/{len(CHECKS)}` checks passed.\n\n"
    "- CI-1 removed: w0 computed for every simple algebra of rank 4-15 plus\n"
    "  E6/E7/E8/F4; the self-conjugacy rules are machine-derived.\n"
    "- Enumeration closed over ALL rank 4-15 simple algebras: the complex\n"
    "  dim-15/16 list is unchanged; so(9)'s 16 and so(15)'s 15 are real\n"
    "  near-misses (fail chirality, not dimension).\n"
    "- CI-4 removed: E6 min = 27, E7 = 56, F4 = 26, E8 = 248 by scan;\n"
    "  rank-16 fundamentals are 17/33/32/32 (> 16).\n"
    "- CI-2 removed: SU(15)/SU(16) fundamental cubic traces are nonzero\n"
    "  (exact integers).\n"
    "- CI-3 removed: the chiral 16 of Spin(10) built from five fermionic\n"
    "  modes has vanishing symmetrized cubic trace over all 45^3 triples;\n"
    "  its Cartan weights reproduce the demicube.\n\n"
    "Boundary: pi_4(Spin(10)) = 0 (Witten global anomaly) is cited, not\n"
    "computed; Frobenius-Schur types are not computed; rank >= 17 minimal\n"
    "dimensions are textbook-cited; zeta is not derived; no PSLT-only\n"
    "unconditional GUT proof is claimed.\n"
)
print(f"Wrote {json_path}")
print(f"Wrote {md_path}")
print(f"Route-E dependency closure: {npass}/{len(CHECKS)} checks passed; "
      "CI-1..CI-4 machine-verified.")
if not all_pass:
    raise SystemExit(1)
